config/routes.rb
Reader::Application.routes.draw do
  resources :documents

  devise_for :users

  root 'pages#index'

end

app/models/document.rb
class Document < ActiveRecord::Base
  belongs_to :user
  attachment :file, extension: "pdf"
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :documents
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    documents_path
  end

end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :set_document, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  respond_to :html

  def index
    @document = Document.new
    @documents = current_user.documents.all
    respond_with(@documents)
  end

  def show
    respond_with(@document)
  end

  def new
    @document = current_user.documents.build
    respond_with(@document)
  end

  def edit
  end

  def create
    @document = current_user.documents.build(document_params)
    @document.save
    redirect_to documents_path
    flash[:notice] = "The document was uploaded successfully."
  end

  def update
    @document.update(document_params)
    respond_with(@document)
  end

  def destroy
    @document.destroy
    respond_with(@document)
  end

  private
    def set_document
      @document = Document.find(params[:id])
    end

    def document_params
      params.require(:document).permit(:file)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/documents/_form.html.erb
<%= form_for(@document) do |f| %>
  <% if @document.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@document.errors.count, "error") %> prohibited this document from being saved:</h2>

      <ul>
      <% @document.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.attachment_field :file %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/documents/edit.html.erb
<h1>Editing document</h1>

<%= render 'form' %>

<%= link_to 'Show', @document %> |
<%= link_to 'Back', documents_path %>

app/views/documents/index.html.erb
<h1>Documents</h1>


<%= form_for @document do |f| %>
  <%= f.attachment_field :file %>
  <%= f.submit "Upload" %>
<% end %>

<ul class="list-group">
  <% if @documents.present? %>
    <% @documents.each do |document| %>
      <%= link_to attachment_url(document, :file), target: "_blank" do %>
          <li class="list-group-item">
            <%= document.file_filename %>
          </li>
      <% end %>
    <% end %>
  <% else %>
    <h3>There are no documents yet...</h3>
  <% end %>
</ul>

app/views/documents/new.html.erb
<h1>New document</h1>

<%= render 'form' %>

<%= link_to 'Back', documents_path %>

app/views/documents/show.html.erb
<p id="notice"><%= notice %></p>
<%= @document.file %>
<%= link_to 'Edit', edit_document_path(@document) %> |
<%= link_to 'Back', documents_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Reader</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<%= yield %>

</body>
</html>

app/views/pages/index.html.erb
This is the home page.

<%= render 'shared/login' %>

app/views/shared/_login.html.erb
<% if user_signed_in? %>
  <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>        
<% else %>
  <%= link_to('Login', new_user_session_path)  %>  
<% end %>